app.startCampaign();
await sleep(2500);
const s = app.session;
const w = s.world;
const me = s.player.tank;
for (const t of w.tanks) if (t.team === 'allies') t.pos.x += 380;
for (const so of w.soldiers) if (so.team === 'allies') so.pos.x += 380;
app.input.ndcX = 0.1; app.input.mouseX = innerWidth * 0.55; app.input.ndcY = -0.1; app.input.mouseY = innerHeight * 0.55;
await sleep(4000);
await window.__shot('before');
const key = (code) => { window.dispatchEvent(new KeyboardEvent('keydown', { code })); setTimeout(() => window.dispatchEvent(new KeyboardEvent('keyup', { code })), 60); };
key('KeyE');
await sleep(4500);
await window.__shot('locked');
const L = s.player.lock;
app.input.lmb = true; await sleep(200); app.input.lmb = false;
await sleep(1200);
await window.__shot('fired');
return { lock: L && (L.callsign || L.role), dist: L && L.pos.distanceTo(me.pos).toFixed(0), autoZoom: s.cam.autoZoom.toFixed(2), reports: w.reports.slice(-3).map(r => `${r.shooter}->${r.targetName}: ${r.headline}`) };
