app.startCampaign();
await sleep(2500);
const s = app.session, r = s.renderer, w = s.world;
s.paused = true;
const fog = r.scene.fog;
for (let i = 0; i < 1200; i++) s.effects.update(1 / 60, fog);
await sleep(800);
const measure = async () => { const t0 = performance.now(); let n = 0; await new Promise(res => { const f = () => { n++; if (performance.now() - t0 < 1500) requestAnimationFrame(f); else res(); }; requestAnimationFrame(f); }); return Math.round(n / 1.5); };
const out = {};
out.base0 = await measure();
await sleep(1500);
out.base = await measure();
out.base2 = await measure();
r.scenePass.dof = false; out.noDof = await measure(); r.scenePass.dof = true;
r.bloom.enabled = false; out.noBloom = await measure(); r.bloom.enabled = true;
const grass = []; w.root.traverse(o => { if (o.isInstancedMesh && o.material.customProgramCacheKey && o.material.customProgramCacheKey() === 'grass-wind') grass.push(o); });
grass.forEach(g => g.visible = false); out.noGrass = await measure(); grass.forEach(g => g.visible = true);
out.grassN = grass.reduce((a, g) => a + g.count, 0);
s.effects.particles.group.visible = false; out.noParticles = await measure(); s.effects.particles.group.visible = true;
r.renderer.shadowMap.autoUpdate = false; out.noShadowUpd = await measure(); r.renderer.shadowMap.autoUpdate = true;
const px = r.renderer.getPixelRatio(); r.renderer.setPixelRatio(1); r.resize(); out.px1 = await measure(); r.renderer.setPixelRatio(px); r.resize();
out.dpr = px;
const info = r.renderer.info.render; out.calls = info.calls; out.tris = info.triangles;
return out;
